default:
  server:
    port: 3000
  spotify: # Sign up and register your "app" here: https://developer.spotify.com/
    client_id: 8407ed3560054e368b2a813754423802
    client_secret: 8cf856157ad64c9aa1fc1cd036f7622c
    redirect_uri: http://192.168.1.101:3000/api/spotify
    refresh_interval: 5000 # ms
  scoreboard:
    refresh_interval: 10000 # ms
development:
  server:
    port: 3001