/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Display: typeof import('./src/components/Display.vue')['default']
    Keyboard: typeof import('./src/components/Keyboard.vue')['default']
    QueueEditor: typeof import('./src/components/QueueEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
